# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Code/TestEend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Code/TestEend/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/david/Code/TestEend/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/david/Code/TestEend/build/CMakeFiles /home/david/Code/TestEend/build/lib/Eendgine//CMakeFiles/progress.marks
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/Eendgine/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Code/TestEend/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/Eendgine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/Eendgine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/Eendgine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/david/Code/TestEend/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/Eendgine/CMakeFiles/Eendgine.dir/rule:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/Eendgine/CMakeFiles/Eendgine.dir/rule
.PHONY : lib/Eendgine/CMakeFiles/Eendgine.dir/rule

# Convenience name for target.
Eendgine: lib/Eendgine/CMakeFiles/Eendgine.dir/rule
.PHONY : Eendgine

# fast build rule for target.
Eendgine/fast:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/build
.PHONY : Eendgine/fast

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/camera.cpp.s
.PHONY : camera.cpp.s

collisionGeometry.o: collisionGeometry.cpp.o
.PHONY : collisionGeometry.o

# target to build an object file
collisionGeometry.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/collisionGeometry.cpp.o
.PHONY : collisionGeometry.cpp.o

collisionGeometry.i: collisionGeometry.cpp.i
.PHONY : collisionGeometry.i

# target to preprocess a source file
collisionGeometry.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/collisionGeometry.cpp.i
.PHONY : collisionGeometry.cpp.i

collisionGeometry.s: collisionGeometry.cpp.s
.PHONY : collisionGeometry.s

# target to generate assembly for a file
collisionGeometry.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/collisionGeometry.cpp.s
.PHONY : collisionGeometry.cpp.s

entityBatches.o: entityBatches.cpp.o
.PHONY : entityBatches.o

# target to build an object file
entityBatches.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/entityBatches.cpp.o
.PHONY : entityBatches.cpp.o

entityBatches.i: entityBatches.cpp.i
.PHONY : entityBatches.i

# target to preprocess a source file
entityBatches.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/entityBatches.cpp.i
.PHONY : entityBatches.cpp.i

entityBatches.s: entityBatches.cpp.s
.PHONY : entityBatches.s

# target to generate assembly for a file
entityBatches.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/entityBatches.cpp.s
.PHONY : entityBatches.cpp.s

fatalError.o: fatalError.cpp.o
.PHONY : fatalError.o

# target to build an object file
fatalError.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/fatalError.cpp.o
.PHONY : fatalError.cpp.o

fatalError.i: fatalError.cpp.i
.PHONY : fatalError.i

# target to preprocess a source file
fatalError.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/fatalError.cpp.i
.PHONY : fatalError.cpp.i

fatalError.s: fatalError.cpp.s
.PHONY : fatalError.s

# target to generate assembly for a file
fatalError.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/fatalError.cpp.s
.PHONY : fatalError.cpp.s

frameLimiter.o: frameLimiter.cpp.o
.PHONY : frameLimiter.o

# target to build an object file
frameLimiter.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/frameLimiter.cpp.o
.PHONY : frameLimiter.cpp.o

frameLimiter.i: frameLimiter.cpp.i
.PHONY : frameLimiter.i

# target to preprocess a source file
frameLimiter.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/frameLimiter.cpp.i
.PHONY : frameLimiter.cpp.i

frameLimiter.s: frameLimiter.cpp.s
.PHONY : frameLimiter.s

# target to generate assembly for a file
frameLimiter.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/frameLimiter.cpp.s
.PHONY : frameLimiter.cpp.s

info.o: info.cpp.o
.PHONY : info.o

# target to build an object file
info.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/info.cpp.o
.PHONY : info.cpp.o

info.i: info.cpp.i
.PHONY : info.i

# target to preprocess a source file
info.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/info.cpp.i
.PHONY : info.cpp.i

info.s: info.cpp.s
.PHONY : info.s

# target to generate assembly for a file
info.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/info.cpp.s
.PHONY : info.cpp.s

inputManager.o: inputManager.cpp.o
.PHONY : inputManager.o

# target to build an object file
inputManager.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/inputManager.cpp.o
.PHONY : inputManager.cpp.o

inputManager.i: inputManager.cpp.i
.PHONY : inputManager.i

# target to preprocess a source file
inputManager.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/inputManager.cpp.i
.PHONY : inputManager.cpp.i

inputManager.s: inputManager.cpp.s
.PHONY : inputManager.s

# target to generate assembly for a file
inputManager.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/inputManager.cpp.s
.PHONY : inputManager.cpp.s

loadModel.o: loadModel.cpp.o
.PHONY : loadModel.o

# target to build an object file
loadModel.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/loadModel.cpp.o
.PHONY : loadModel.cpp.o

loadModel.i: loadModel.cpp.i
.PHONY : loadModel.i

# target to preprocess a source file
loadModel.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/loadModel.cpp.i
.PHONY : loadModel.cpp.i

loadModel.s: loadModel.cpp.s
.PHONY : loadModel.s

# target to generate assembly for a file
loadModel.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/loadModel.cpp.s
.PHONY : loadModel.cpp.s

model.o: model.cpp.o
.PHONY : model.o

# target to build an object file
model.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i
.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s
.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/model.cpp.s
.PHONY : model.cpp.s

random.o: random.cpp.o
.PHONY : random.o

# target to build an object file
random.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i
.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s
.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/random.cpp.s
.PHONY : random.cpp.s

screen.o: screen.cpp.o
.PHONY : screen.o

# target to build an object file
screen.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/screen.cpp.o
.PHONY : screen.cpp.o

screen.i: screen.cpp.i
.PHONY : screen.i

# target to preprocess a source file
screen.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/screen.cpp.i
.PHONY : screen.cpp.i

screen.s: screen.cpp.s
.PHONY : screen.s

# target to generate assembly for a file
screen.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/screen.cpp.s
.PHONY : screen.cpp.s

shader.o: shader.cpp.o
.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i
.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s
.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shader.cpp.s
.PHONY : shader.cpp.s

shaders.o: shaders.cpp.o
.PHONY : shaders.o

# target to build an object file
shaders.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shaders.cpp.o
.PHONY : shaders.cpp.o

shaders.i: shaders.cpp.i
.PHONY : shaders.i

# target to preprocess a source file
shaders.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shaders.cpp.i
.PHONY : shaders.cpp.i

shaders.s: shaders.cpp.s
.PHONY : shaders.s

# target to generate assembly for a file
shaders.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/shaders.cpp.s
.PHONY : shaders.cpp.s

sprite.o: sprite.cpp.o
.PHONY : sprite.o

# target to build an object file
sprite.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/sprite.cpp.o
.PHONY : sprite.cpp.o

sprite.i: sprite.cpp.i
.PHONY : sprite.i

# target to preprocess a source file
sprite.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/sprite.cpp.i
.PHONY : sprite.cpp.i

sprite.s: sprite.cpp.s
.PHONY : sprite.s

# target to generate assembly for a file
sprite.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/sprite.cpp.s
.PHONY : sprite.cpp.s

texture.o: texture.cpp.o
.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i
.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/texture.cpp.s
.PHONY : texture.cpp.s

textureCache.o: textureCache.cpp.o
.PHONY : textureCache.o

# target to build an object file
textureCache.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/textureCache.cpp.o
.PHONY : textureCache.cpp.o

textureCache.i: textureCache.cpp.i
.PHONY : textureCache.i

# target to preprocess a source file
textureCache.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/textureCache.cpp.i
.PHONY : textureCache.cpp.i

textureCache.s: textureCache.cpp.s
.PHONY : textureCache.s

# target to generate assembly for a file
textureCache.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/textureCache.cpp.s
.PHONY : textureCache.cpp.s

window.o: window.cpp.o
.PHONY : window.o

# target to build an object file
window.cpp.o:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i
.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s
.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	cd /home/david/Code/TestEend/build && $(MAKE) $(MAKESILENT) -f lib/Eendgine/CMakeFiles/Eendgine.dir/build.make lib/Eendgine/CMakeFiles/Eendgine.dir/window.cpp.s
.PHONY : window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Eendgine"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... collisionGeometry.o"
	@echo "... collisionGeometry.i"
	@echo "... collisionGeometry.s"
	@echo "... entityBatches.o"
	@echo "... entityBatches.i"
	@echo "... entityBatches.s"
	@echo "... fatalError.o"
	@echo "... fatalError.i"
	@echo "... fatalError.s"
	@echo "... frameLimiter.o"
	@echo "... frameLimiter.i"
	@echo "... frameLimiter.s"
	@echo "... info.o"
	@echo "... info.i"
	@echo "... info.s"
	@echo "... inputManager.o"
	@echo "... inputManager.i"
	@echo "... inputManager.s"
	@echo "... loadModel.o"
	@echo "... loadModel.i"
	@echo "... loadModel.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... screen.o"
	@echo "... screen.i"
	@echo "... screen.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... shaders.o"
	@echo "... shaders.i"
	@echo "... shaders.s"
	@echo "... sprite.o"
	@echo "... sprite.i"
	@echo "... sprite.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... textureCache.o"
	@echo "... textureCache.i"
	@echo "... textureCache.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/david/Code/TestEend/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

